name = "monfolio-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "monfolio-local-db"
database_id = "eecca0cb-28a3-4be2-aaec-03d1cdf15b53"

[env.development]
name = "monfolio-server-dev"

[[env.development.d1_databases]]
binding = "DB"
database_name = "monfolio-local-db"
database_id = "eecca0cb-28a3-4be2-aaec-03d1cdf15b53"

[env.production]
name = "monfolio-server"

[[env.production.d1_databases]]
binding = "DB"
database_name = "monfolio-production-db"
database_id = "07884dec-69ee-47a0-bb7b-6eaca8d5b041"

[vars]
CORS_ORIGIN = "http://localhost:3001"

# API keys moved to Cloudflare Workers secrets for security
# Use: wrangler secret put ETHERSCAN_API_KEY
# Use: wrangler secret put COINGECKO_API_KEY